require: rubocop-rails
AllCops:
  TargetRubyVersion: '3.1.2'
  NewCops: enable
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Lint/MissingCopEnableDirective:
  Enabled: false
